### ISSUE TITLE
[Suggestions/Requests]

### ISSUE THREAD

**Issue by CatsArmy** [risk-of-thunder/BepInEx.GUI#21]
Soo i got it working
but now i realize a few things

1. there is no way to change to icon at least that i know of
2. it doesnt support more ascii characters

soooooo if there could be way to change the icon that would be helpful
note i dont know rust and i dont have a enviorment to build rust stuff in so yee

**Comment by xiaoxiao921** [comment]
People have changed the icons just fine in the past before, check that repo for examples https://github.com/Govorunb/BepInEx.GUI

Closing because this is not an issue with the project itself.

**Comment by CatsArmy** [comment]
wait wat
wont changing the icon require having a rust env?

**Comment by CatsArmy** [comment]
nvm ill just use this as a reason to learn how to build rust tyyyy
