### ISSUE TITLE
Gui crashes when using Async Loggers Timestamps

### ISSUE THREAD

**Issue by CatsArmy** [risk-of-thunder/BepInEx.GUI#23]
I've been trying to fix this issue for a while now but i cant figure out why its happening so i thought it was just happening on my fork of the mod but now i tested it here too and it crashes the GUI after a few seconds.

## Some context about the [bug](https://github.com/mattymatty97/LTC_AsyncLoggers/issues/3):
This bug occurrences when and only when [Async Loggers]](https://thunderstore.io/c/lethal-company/p/mattymatty/AsyncLoggers/)(Multi game mod (rounds and LC but works with more has the timestamps enabled.
```
[22:24:58.5779115] [Error  :BepInEx.GUI.Loader] Error while trying to send log to socket: System.Net.Sockets.SocketException (0x80004005): Connection reset by peer
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) [0x00016] in <6b80e2850f1c48e6a227f0818ca6b227>:IL_0016 
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer) [0x00000] in <6b80e2850f1c48e6a227f0818ca6b227>:IL_0000 
  at BepInEx.GUI.Loader.SendLogToClientSocket.SendPacketsToClientUntilConnectionIsClosed (System.Net.Sockets.Socket clientSocket) [0x0003d] in <1bdf28b1593443dcb8ec24f9e13cdb6a>:IL_003D 
Disconnecting socket.
 ```
 
 ## What Async Loggers is doing:
The way Async Loggers implements the Async functionality as following:
[he wraps all log listeners with a Job/Thread(based on config)](https://github.com/mattymatty97/LTC_AsyncLoggers/blob/preloader/AsyncLoggers/src/Patches/BepInExLoggerPatcher.cs#L21). I don't believe this should not be causing the issue from what I can tell. a potential cause for the issue is the patching of the ToString() method of the LogEventArgs which may be somehow messing with the way that the LogPacket is calculating the byte[] Length somehow causing an overflow potentially even on the GUI side(unsure of this though).
 
 [The Patch:](https://github.com/mattymatty97/LTC_AsyncLoggers/blob/preloader/AsyncLoggers/src/Patches/BepInExLogEventArgsPatch.cs#L19)
 ```c#
  [HarmonyPostfix]
        [HarmonyPatch(typeof(LogEventArgs), nameof(LogEventArgs.ToString))]
        private static void PrependTimestamp(LogEventArgs __instance, ref string __result)
        {
            if (PluginConfig.Timestamps.Enabled.Value && 
                CONTEXTS.TryGetValue(__instance, out var logContext))
            {
                __result = $"[{logContext.Timestamp}] {__result}";
            }
        }
 ```
 
I am totally lost on the why this is even crashing when the config is enabled. Originally I suspected it was something to do with the way he was getting the Timestamps into the LogEventArg by patching the ToString of it, but after looking at the error in the logs I don't think that is it.

**Comment by xiaoxiao921** [comment]
This has nothing to do with this repo itself, I'll continue the discussion in the issue you linked.
